### ISSUE TITLE
_user$project$Native_IpcRenderer is not defined

### ISSUE THREAD

**Issue by oleiade** [elm-electron/elm-electron#1]
Hi!

First of all thanks for this project, it's really helping to get started with Elm and Electron!

I'm currently trying to use the `IpcRenderer.elm` you created with Elm 0.17. Everything compiles on elm side. But when I run electron, and use `IpcRenderer.send` function, I get a runtime error:
```javascript
elm.js:8597 Uncaught ReferenceError: _user$project$Native_IpcRenderer is not defined
```

Being no expert in JS I have a hard time finding out where the problem comes from. I had thought that maybe the runtime could not find the ```_elm_electron$elm_electron$Native_IpcRenderer``` function you declare in `Native/IpcRenderer.js`, but after adding some `console.log` here and there, I realize that the function is actually being called.

Any ideas where to search? :-)
Thanks~

**Comment by oleiade** [comment]
So, after some more digging, it occurs that for some reason, when compiling with your `Native/IpcRenderer.js`, the elm compiler expects the function calls to be of the form `_user$project$Native_IpcRenderer`.

I found that by digging into the generated JS, exploring, and watching this: https://elmseeds.thaterikperson.com/native-modules

Now, I'm not sure my case is generalizable, but it seems the way to go is to rename the main function of `Native/IpcRenderer.js` to 
```javascript
var _user$project$Native_IpcRenderer = (function () {
  var ipcRenderer = require('electron').ipcRenderer;
  // ...
}
```
 
Also, now that I've got a working example, where would be the proper place to submit an example, for wanderers like me to have their experience eased in the future? :-)

**Comment by lukewestby** [comment]
@oleiade hey! i'm not really working on this stuff lately. if you want i can add you to the org and you can change stuff as you like. sound good?

**Comment by oleiade** [comment]
Hey @lukewestby 

Sure thing! Would be great!

Also tried to reach you on slack, got a question about how to subscribe with `on` function. Would be great to get your input if you've got time and remember how this works :-)

**Comment by lukewestby** [comment]
@oleiade definitely, i'll be on slack shortly
